### PR TITLE
Added "how to start" to README (issue #15)

### PR DESCRIPTION
**Pull request by motrell**
We added a short documentation, how to run our services. Please let us know, if we forgot sth. or you want more details.

### CODE REVIEW

**Comment by motrell** [comment]
Just noticed, that we did not follow the checklist from #15

**Comment by Amir-Hussein-OTH** [comment]
Nice

**Review by Amir-Hussein-OTH — APPROVED** [review]

**Review by leondaniel22 — APPROVED** [review]
Looks good so far!
For the future we need to add the following:
- how to add the env-file in order to connect to the mdh

**Comment by motrell** [comment]
We just pushed an updated version. Please have again a look on it. Maybe, we can also talk about it later in the dev meeting.

**Comment by motrell** [comment]
Just let us know on any way, if something is missing

**Review by martin-mtv — APPROVED** [review]
Looks good to me!

**Pull request merged**
