### PR TITLE
Include statistics

### PR DESCRIPTION
**Pull request by oninach**
enable multipe data visualization that are created in OS-Dashboard.

### CODE REVIEW

**Comment by martin-mtv** [comment]
We implemented the feature as described in the #36. We took care to comment the code and build an appealing frontend.

**Review by Amir-Hussein-OTH — APPROVED** [review]

**Review by Amir-Hussein-OTH — CHANGES_REQUESTED** [review]
A lot of commits for ta smal changes.  Please consider **squashing**  [https://git-scm.com/book/en/v2/Git-Tools-Rewriting-History] the multiple commits into a single commit for better code organization.

 It's preferable to have fewer commits when the changes are minimal or when they can be logically grouped together. 

This will help maintain a cleaner commit history and make it easier for reviewers to understand the changes made. Thank you for your attention to this matter.

**Review by Amir-Hussein-OTH — APPROVED** [review]

**Comment by motrell** [comment]
> A lot of commits for small changes. **Next time!** Please consider **squashing** ( https://git-scm.com/book/en/v2/Git-Tools-Rewriting-History) the multiple commits into a single commit for better code organization.
> 
> It's preferable to have fewer commits when the changes are minimal or when they can be logically grouped together.
> 
> This will help maintain a cleaner commit history and make it easier for reviewers to understand the changes made. Thank you for your attention to this matter.

tbh., I don't think so. There is no need to go through every commit by itself, you can just have a look at the "Files changed"-Section (or by a single use of `git diff`) to see all changes at once.

In Addition, smaller commits make it easier to revert single changes, if they where not necessary.

If you like to, we can discuss this in person, maybe this is a better place than this pull request, at least for a longer discussion

**Comment by leondaniel22** [comment]
I think the visualization looks good so far. Therefore we can merge this branch into main!

**Comment by JMiltner97** [comment]
I like it. I will merge it into main for the release shortly

**Review by JMiltner97 — APPROVED** [review]

**Pull request merged**
