### PR TITLE
Added functionality for pagination

### PR DESCRIPTION
**Pull request by JMiltner97**

### CODE REVIEW

**Comment by JMiltner97** [comment]
Please review this functionality and test critically as it is a complicated feature

**Review by motrell — APPROVED** [review]
Looks good, nice work!

Some suggestions for improvements (not neccessary for the current sprint):
- Start the page index by 1 (for "normal" humans, so that not only informaticians are happy)
- Replace the Hitcount by an concrete numeric index over all pages, so that it doesn't remain "1-10" on every page.

@lukas-rotsching @tawfeeka maybe you're also interested.

**Review by martin-mtv — APPROVED** [review]
Good addititon to our project! We could think about limiting the number of pages you can visit in the future. As of now you can visit an unlimited amount of empty pages

**Comment by oninach** [comment]
Overall great Work !
One important feature is not working while testing : the show details button, it's seems that it has some bugs.
@motrell @martin-mtv did you test that as well ?

one more thing that we can add is maybe to make the next button disable in case there is no more results(but not important as the show button).

**Review by leondaniel22 — APPROVED** [review]
I tested it and the functionality works fine so far. Good job. :)

**Comment by motrell** [comment]
> Overall great Work ! One important feature is not working while testing : the show details button, it's seems that it has some bugs. @motrell @martin-mtv did you test that as well ?

Sadly, you're right @oninach

**Review by Amir-Hussein-OTH — APPROVED** [review]

**Pull request merged**
