### PR TITLE
Corrected the logo of our website (now MdH-OS)

### PR DESCRIPTION
**Pull request by motrell**
Just changed the logo of our website to the correct abbreviation, it is now "MdH-OS".

### CODE REVIEW

**Review by Amir-Hussein-OTH — CHANGES_REQUESTED** [review]
Lintpy is flagging the exception handling in our code as being too general. 

I have updated the exception handling in the get_datatype & field_exists methods to catch OpenSearchException specifically. 

This allows you to handle exceptions related to OpenSearch operations more precisely.

**Comment by motrell** [comment]
> Lintpy is flagging the exception handling in our code as being too general.
> 
> I have updated the exception handling in the get_datatype & field_exists methods to catch OpenSearchException specifically.
> 
> This allows you to handle exceptions related to OpenSearch operations more precisely.

@Amir and me decided to handle this issue in another branch, so that we stay with the philosophy "one feature/fix per branch".

**Review by martin-mtv — APPROVED** [review]
Looks good, we can merge this branch into main

**Review by leondaniel22 — APPROVED** [review]

**Review by oninach — APPROVED** [review]

**Comment by JMiltner97** [comment]
Looks good to me

**Review by JMiltner97 — APPROVED** [review]

**Pull request merged**
