### PR TITLE
Refactor dashboard api

### PR DESCRIPTION
**Pull request by martin-mtv**
I created an OpenSearch-Dashboard Manager class similar to the OpenSearch Manager

### CODE REVIEW

**Review by motrell — APPROVED** [review]
looks good!

**Review by Amir-Hussein-OTH — APPROVED** [review]

**Review by leondaniel22 — APPROVED** [review]
Very good code!

**Review by JMiltner97 — COMMENTED** [review]
Looks good 👍

**Review by JMiltner97 — APPROVED** [review]

**Review by motrell — APPROVED** [review]
Nice!

**Pull request merged**
