### PR TITLE
Nice looking website

### PR DESCRIPTION
**Pull request by JMiltner97**
Please review the merge of our new website to the main branch

### CODE REVIEW

**Comment by Amir-Hussein-OTH** [comment]
>

**Comment by Amir-Hussein-OTH** [comment]
> Please review the merge of our new website to the main branch

After reviewing the code, it seems that there may be an issue with the search functionality on the website. When entering text and clicking on the search button, the website fails to perform the search as expected.

To resolve this issue, I would suggest checking the following areas:

Verify that the HTML form element responsible for handling the search input and button is correctly set up. Ensure that the form has the appropriate action and method attributes defined.

Check the JavaScript code responsible for capturing the search input and triggering the search functionality. Ensure that the event listener is properly attached to the search button, and that it calls the correct function.

Check for any error messages or warnings in the browser's console when attempting to perform a search. These can provide valuable insights into any potential issues with the code.

**Comment by JMiltner97** [comment]
You need to make sure your docker is running the correct image. Please delete them before starting your containers.
I'll make another small adjustment and reopen the pull request

**Comment by Amir-Hussein-OTH** [comment]
> You need to make sure your docker is running the correct image. Please delete them before starting your containers. I'll make another small adjustment and reopen the pull request
> 
> > > Please review the merge of our new website to the main branch
> > 
> > 
> > After reviewing the code, it seems that there may be an issue with the search functionality on the website. When entering text and clicking on the search button, the website fails to perform the search as expected.
> > To resolve this issue, I would suggest checking the following areas:
> > Verify that the HTML form element responsible for handling the search input and button is correctly set up. Ensure that the form has the appropriate action and method attributes defined.
> > Check the JavaScript code responsible for capturing the search input and triggering the search functionality. Ensure that the event listener is properly attached to the search button, and that it calls the correct function.
> > Check for any error messages or warnings in the browser's console when attempting to perform a search. These can provide valuable insights into any potential issues with the code.


> You need to make sure your docker is running the correct image. Please delete them before starting your containers. I'll make another small adjustment and reopen the pull request
> 
> > > Please review the merge of our new website to the main branch
> > 
> > 
> > After reviewing the code, it seems that there may be an issue with the search functionality on the website. When entering text and clicking on the search button, the website fails to perform the search as expected.
> > To resolve this issue, I would suggest checking the following areas:
> > Verify that the HTML form element responsible for handling the search input and button is correctly set up. Ensure that the form has the appropriate action and method attributes defined.
> > Check the JavaScript code responsible for capturing the search input and triggering the search functionality. Ensure that the event listener is properly attached to the search button, and that it calls the correct function.
> > Check for any error messages or warnings in the browser's console when attempting to perform a search. These can provide valuable insights into any potential issues with the code.


I noticed that there are two search fields present on the website instead of just one. It appears that you may have forgotten to remove one of them during development.

Once you have removed the extra search field, the website should only have one search field, and clicking on the search button should perform the search as intended. Thanks for the good job 👍

**Review by Amir-Hussein-OTH — APPROVED** [review]

**Review by martin-mtv — APPROVED** [review]
Looks good!

**Comment by motrell** [comment]
Just changed the base branch. See [here](https://github.com/amosproj/amos2023ss02-open-search-meta-data-hub/pull/41#issuecomment-1558712573) for reason.

**Pull request merged**
