### PR TITLE
Define versions for all libraries

### PR DESCRIPTION
**Pull request by martin-mtv**
This change ensures deterministic behaviour of the libraries in the future.

### CODE REVIEW

**Review by motrell — COMMENTED** [review]
Looks good. I will test it again after merging the other 2 branches.

**Comment by JMiltner97** [comment]
Looks good to me so 👍🏾

**Review by leondaniel22 — APPROVED** [review]
Thanks @martin-mtv for doing this. Looks very good!

**Review by JMiltner97 — APPROVED** [review]

**Comment by motrell** [comment]
> Looks good. I will test it again after merging the other 2 branches.

No problems luckily.

**Pull request merged**
