### PR TITLE
Implement efficient data transportation

### PR DESCRIPTION
**Pull request by leondaniel22**
We implemented a version of our import script that is able to import data from mdh efficiently by using the _bulk API from OS

### CODE REVIEW

**Comment by JMiltner97** [comment]
Looks good to me so far

**Review by JMiltner97 — APPROVED** [review]

**Comment by Amir-Hussein-OTH** [comment]
> Looks good. But shouldn't we first merge everything in the flask-webserver-branch?

Yes, you are correct. Before proceeding with other features, it is recommended to merge all the changes and updates  into the flask-webserver-branch and then into the main branch. This ensures that the latest code and modifications are incorporated into the main codebase.

**Comment by martin-mtv** [comment]
I resolved the merge conflicts

**Review by martin-mtv — CHANGES_REQUESTED** [review]
I tried to test the feature, but it seems that the import script dosen't work anymore.

**Comment by motrell** [comment]
> I tried to test the feature, but it seems that the import script dosen't work anymore.

Same for me, Some ConnectionError after much time.

**Comment by Amir-Hussein-OTH** [comment]
> ConnectionError

Can you provide more details about the import script and the specific issue you encountered? This will help me better understand the problem and provide you with appropriate assistance.

**Review by martin-mtv — APPROVED** [review]

**Pull request merged**
